variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
- master

pool:
  name: AWS
  demands:
   - agent.name -equals aws

steps:
  - task: Cache@2
    displayName: 'Cache Maven local repo'
    inputs:
      key: '"funcs" | maven | "$(Agent.OS)" | pom.xml'
      restoreKeys: |
      path: $(MAVEN_CACHE_FOLDER)

  - task: Maven@3
    displayName: 'Build and Test'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: package
      mavenVersionSelection: Path
      mavenPath: /opt/maven
      mavenOptions: '-Xmx2048m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
